/* Generated By:JavaCC: Do not edit this line. IndexConstants.java */



/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IndexConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INPUT = 9;
  /** RegularExpression Id. */
  int OUTPUT = 10;
  /** RegularExpression Id. */
  int TXT = 11;
  /** RegularExpression Id. */
  int chiffre = 12;
  /** RegularExpression Id. */
  int entier = 13;
  /** RegularExpression Id. */
  int lettre = 14;
  /** RegularExpression Id. */
  int ident = 15;
  /** RegularExpression Id. */
  int chaine = 16;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"-\"",
    "\"\\r\"",
    "\"(*\"",
    "<token of kind 7>",
    "\"*)\"",
    "\"input\"",
    "\"output\"",
    "\".txt\"",
    "<chiffre>",
    "<entier>",
    "<lettre>",
    "<ident>",
    "<chaine>",
    "\",\"",
  };

}
